@host=https://localhost:7071
@admin=CHWZZpHheIb5arl5uQRdSWqlOhqFuVJVqZLXVJGMjRjmBpDocnQFMN831GDUcoFdNNqsLvyvMPhMfgTnhZf
@user1=9nptmxiQXQAruA7fvMiAvreQ5aPci4d2FlRjd9WaScZogvznQRZGTjWQ0uB8FInsHs1zLP3N52IM6MbgvTW
@user2=9xxJM9FBeSRdyo4ajwKMx49vn15i7Efyfvao39ieRdbN0mWcxCd17FGUPlFdNaQDFe3aMEkCGSVbFt87HIz

###
GET {{host}}/booking

###
POST {{host}}/booking
Content-Type: application/json
ApiKey:{{user2}}

{
  "time": "2025-08-24T16:00:00",
  "period": 30,
  "type": "Masszázs-1"
}